## Import Libraries 

In [ ]:
import pandas as pd
import numpy as np

np.set_printoptions(suppress=True)

## Import the dataset

In [5]:
df= pd.read_csv('GDL_Indicators_(2019)_data.csv')
df

Country ISO_Code     Level GDLCODE Region  \
0                    Burundi      BDI  National    BDIt  Total   
1  Congo Democratic Republic      COD  National    CODt  Total   
2                      Kenya      KEN  National    KENt  Total   
3                     Rwanda      RWA  National    RWAt  Total   
4                South Sudan      SSD  National    SSDt  Total   
5                   Tanzania      TZA  National    TZAt  Total   
6                     Uganda      UGA  National    UGAt  Total   

   Life expectancy  Life expectancy females  Life expectancy males  \
0             61.6                     63.4                   59.8   
1             60.7                     62.2                   59.1   
2             66.7                     69.0                   64.3   
3             69.0                     71.1                   66.8   
4             57.9                     59.4                   56.4   
5             65.5                     67.2                   63.6   
6             63.4                     65.6                   61.0   

   Expected years schooling  Expected years schooling girls  \
0                      11.1                            11.0   
1                       9.7                             8.6   
2                      11.3                            11.0   
3                      11.2                            11.2   
4                       5.3                             3.5   
5                       8.1                             8.2   
6                      11.4                            10.6   

   Expected years schooling boys  Mean years schooling  \
0                           11.1                   3.3   
1                           10.8                   6.8   
2                           11.7                   6.6   
3                           11.2                   4.4   
4                            5.9                   4.8   
5                            8.0                   6.1   
6                           12.2                   6.2   

   Mean years schooling females  Mean years schooling males  \
0                           2.6                         4.1   
1                           5.3                         8.4   
2                           6.0                         7.2   
3                           4.0                         4.9   
4                           3.9                         5.2   
5                           5.8                         6.4   
6                           4.9                         7.6   

   GNI per capita in thousands of US$ (2011 PPP)  \
0                                          6.625   
1                                          6.969   
2                                          8.353   
3                                          7.676   
4                                          7.602   
5                                          7.863   
6                                          7.661   

   Log Gross National Income per capita females  \
0                                         6.764   
1                                         6.810   
2                                         8.207   
3                                         7.537   
4                                         7.473   
5                                         7.706   
6                                         7.372   

   Log Gross National Income per capita males  Population size in thousands  
0                                       6.461                         11531  
1                                       7.105                         86791  
2                                       8.482                         52574  
3                                       7.801                         12627  
4                                       7.717                         11062  
5                                       7.999                         58005  
6                                       7.890                         44270

## Define the dataset

In [17]:
X = df[['Life expectancy','Mean years schooling','Population size in thousands','GNI per capita in thousands of US$ (2011 PPP)']].values
X

array([[   61.6  ,     3.3  , 11531.   ,     6.625],
       [   60.7  ,     6.8  , 86791.   ,     6.969],
       [   66.7  ,     6.6  , 52574.   ,     8.353],
       [   69.   ,     4.4  , 12627.   ,     7.676],
       [   57.9  ,     4.8  , 11062.   ,     7.602],
       [   65.5  ,     6.1  , 58005.   ,     7.863],
       [   63.4  ,     6.2  , 44270.   ,     7.661]])

## Scale the data between o-1

In [18]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X_scaled = sc_X.fit_transform(X)
X_scaled

array([[-0.55016109, -1.78029401, -1.03955927, -1.71844925],
       [-0.80501513,  1.1082625 ,  1.75259042, -1.06924533],
       [ 0.89401177,  0.94320212,  0.48313804,  1.54266812],
       [ 1.54530542, -0.87246197, -0.99889762,  0.26501971],
       [-1.59789435, -0.54234122, -1.0569592 ,  0.12536538],
       [ 0.55420639,  0.53055119,  0.6846284 ,  0.61792998],
       [-0.04045302,  0.61308138,  0.17505923,  0.2367114 ]])

## Use PCA to reduce dimensionality

In [19]:
from sklearn.decomposition import PCA
pca = PCA(n_components=None)
X_scaled = pca.fit_transform(X_scaled)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)
print(pca.components_.T * np.sqrt(pca.explained_variance_))


[0.53589141 0.33798283 0.12221815 0.00390761]
[[-0.44304695 -0.84417984 -0.50734725  0.0183094 ]
 [-1.01881661  0.32676761  0.11349874  0.09497551]
 [-0.85673917  0.59179059 -0.27576376 -0.08001821]
 [-0.72975797 -0.63845159  0.47331017 -0.04976968]]
